services:
  onlyoffice-frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: onlyoffice-frontend
    ports:
      - "5001:5001" # Client
      - "5011:5011" # Login
      - "5013:5013" # DocEditor
      - "5015:5015" # Management
      - "5099:5099" # SDK
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  default:
    name: onlyoffice
    external: false
